// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models;

namespace Shmear.EntityFramework.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20201126193724_card")]
    partial class card
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DealerPlayerId");

                    b.Property<int>("GameId");

                    b.Property<int?>("Team1Wager");

                    b.Property<int?>("Team2Wager");

                    b.Property<int?>("TrumpSuitId");

                    b.HasKey("Id");

                    b.HasIndex("DealerPlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("TrumpSuitId");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SuitId");

                    b.Property<int>("ValueId");

                    b.HasKey("Id");

                    b.HasIndex("SuitId");

                    b.HasIndex("ValueId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Team1Points");

                    b.Property<int>("Team2Points");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.GamePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId");

                    b.Property<int>("PlayerId");

                    b.Property<bool>("Ready");

                    b.Property<int>("SeatNumber");

                    b.Property<int?>("Wager");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamePlayer");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.HandCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId");

                    b.Property<int>("GameId");

                    b.Property<int>("PlayerId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("HandCard");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<DateTime>("KeepAlive")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.PlayerComputer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("PlayerId");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerComputer");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Suit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Suit");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Trick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("GameId");

                    b.Property<int>("Sequence");

                    b.Property<int?>("WinningPlayerId");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("WinningPlayerId");

                    b.ToTable("Trick");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.TrickCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId");

                    b.Property<int>("PlayerId");

                    b.Property<int>("Sequence");

                    b.Property<int>("TrickId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrickId");

                    b.ToTable("TrickCard");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Points");

                    b.Property<int>("Sequence");

                    b.HasKey("Id");

                    b.ToTable("Value");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Board", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", "DealerPlayer")
                        .WithMany("Board")
                        .HasForeignKey("DealerPlayerId")
                        .HasConstraintName("FK_Board_Player");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Game", "Game")
                        .WithMany("Board")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Board_Game");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Suit", "TrumpSuit")
                        .WithMany("Board")
                        .HasForeignKey("TrumpSuitId")
                        .HasConstraintName("FK_Board_Suit");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Card", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Suit", "Suit")
                        .WithMany("Card")
                        .HasForeignKey("SuitId")
                        .HasConstraintName("FK_Card_Suit");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Value", "Value")
                        .WithMany("Card")
                        .HasForeignKey("ValueId")
                        .HasConstraintName("FK_Card_Value");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.GamePlayer", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Game", "Game")
                        .WithMany("GamePlayer")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_GamePlayer_Game");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", "Player")
                        .WithMany("GamePlayer")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_GamePlayer_Player");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.HandCard", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Card", "Card")
                        .WithMany("HandCard")
                        .HasForeignKey("CardId")
                        .HasConstraintName("FK_HandCard_Card");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Game", "Game")
                        .WithMany("HandCard")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_HandCard_Game");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", "Player")
                        .WithMany("HandCard")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_HandCard_Player");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.PlayerComputer", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", "Player")
                        .WithMany("PlayerComputer")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_PlayerComputer_Player");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Trick", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Game", "Game")
                        .WithMany("Trick")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Trick_Game");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", "WinningPlayer")
                        .WithMany("Trick")
                        .HasForeignKey("WinningPlayerId")
                        .HasConstraintName("FK_Trick_Player");
                });

            modelBuilder.Entity("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.TrickCard", b =>
                {
                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Card", "Card")
                        .WithMany("TrickCard")
                        .HasForeignKey("CardId")
                        .HasConstraintName("FK_TrickCard_Card");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Player", "Player")
                        .WithMany("TrickCard")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_TrickCard_Player");

                    b.HasOne("Shmear.EntityFramework.EntityFrameworkCore.SqlServer.Models.Trick", "Trick")
                        .WithMany("TrickCard")
                        .HasForeignKey("TrickId")
                        .HasConstraintName("FK_TrickCard_Trick");
                });
#pragma warning restore 612, 618
        }
    }
}
